from __future__ import annotations


TEMPLATE_LIBRARY_CATEGORIES = [
    "日常行政型",
    "專案活動型",
    "社團運作型",
    "財務與清冊型",
]

FORMAL_TEMPLATE_FORBIDDEN_BODY_TEXT = [
    "範本類型",
    "建議格式",
    "對應評鑑分類",
    "使用情境",
    "使用說明",
    "系統自動化說明",
    "專案管理說明",
    "template key",
    "metadata",
    "renderer",
    "生成文件頁",
    "自動產生評鑑 ZIP",
]


def _entry(
    template_key: str,
    display_name: str,
    aliases: list[str],
    category: str,
    format_name: str,
    priority: str,
    supports_blank_download: bool,
    supports_generate_document: bool,
    short_description: str,
    implementation_status: str,
    *,
    legacy_definition_id: str | None = None,
    linked_document_type: str | None = None,
    preview_type: str | None = None,
    evaluation_category: str = "",
) -> dict:
    extension_dir = "odt" if format_name == "ODT" else "ods"
    return {
        "template_key": template_key,
        "display_name": display_name,
        "aliases": aliases,
        "category": category,
        "format": format_name,
        "priority": priority,
        "supports_blank_download": supports_blank_download,
        "supports_generate_document": supports_generate_document,
        "spec_path": f"docs/template_specs/{template_key}_spec.md",
        "blank_template_path": f"templates/{extension_dir}/{template_key}.{format_name.lower()}",
        "renderer": f"render_{template_key}",
        "preview_type": preview_type or ("odt_preview" if format_name == "ODT" else "ods_preview"),
        "implementation_status": implementation_status,
        "short_description": short_description,
        "legacy_definition_id": legacy_definition_id,
        "linked_document_type": linked_document_type,
        "evaluation_category": evaluation_category,
        "forbidden_body_text": FORMAL_TEMPLATE_FORBIDDEN_BODY_TEXT,
    }


FORMAL_TEMPLATE_REGISTRY = [
    _entry(
        "meeting_minutes",
        "會議紀錄",
        ["會議記錄", "meeting_minutes_template_odt"],
        "日常行政型",
        "ODT",
        "最高",
        True,
        True,
        "記錄會議報告、討論事項、決議與表決結果。",
        "implemented",
        legacy_definition_id="meeting_minutes_template_odt",
        linked_document_type="會議紀錄",
        preview_type="meeting_minutes",
        evaluation_category="2.社團行政_管理運作",
    ),
    _entry(
        "meeting_notice",
        "開會通知單",
        ["會議通知", "開會通知", "meeting_notice_odt"],
        "日常行政型",
        "ODT",
        "高",
        True,
        True,
        "發送正式會議時間、地點、出席者與附件通知。",
        "implemented",
        legacy_definition_id="meeting_notice_odt",
        linked_document_type="開會通知單",
        preview_type="meeting_notice",
        evaluation_category="2.社團行政_管理運作",
    ),
    _entry(
        "meeting_agenda",
        "會議議程",
        ["meeting_agenda_odt"],
        "日常行政型",
        "ODT",
        "高",
        False,
        True,
        "安排會議流程、報告事項與討論事項。",
        "partial",
        legacy_definition_id="meeting_agenda_odt",
        linked_document_type="會議議程",
        evaluation_category="2.社團行政_管理運作",
    ),
    _entry(
        "attendance_sheet",
        "簽到表",
        ["出席簽到表", "attendance_sheet_ods"],
        "日常行政型",
        "ODT",
        "高",
        False,
        False,
        "提供活動、社課或會議現場簽到使用。",
        "registered_only",
    ),
    _entry(
        "club_announcement",
        "社團公告／通知",
        ["club_announcement_odt"],
        "日常行政型",
        "ODT",
        "中高",
        False,
        False,
        "發布一般社團公告、活動提醒與行政通知。",
        "registered_only",
    ),
    _entry(
        "activity_proposal",
        "活動企畫書",
        ["活動企劃書", "activity_proposal_odt"],
        "專案活動型",
        "ODT",
        "最高",
        True,
        True,
        "撰寫活動宗旨、內容、流程、分工與預算。",
        "implemented",
        legacy_definition_id="activity_proposal_odt",
        linked_document_type="活動企劃書",
        preview_type="activity_proposal",
        evaluation_category="6.社團活動_社團活動",
    ),
    _entry(
        "activity_application",
        "活動申請表",
        ["activity_application_odt"],
        "專案活動型",
        "ODT",
        "最高",
        False,
        False,
        "依學校格式整理活動申請與行政審核資料。",
        "registered_only",
    ),
    _entry(
        "activity_result_report",
        "活動成果報告",
        ["社團活動成果報告", "活動成果報告書", "成果報告", "activity_report_odt"],
        "專案活動型",
        "ODT",
        "最高",
        True,
        True,
        "整理活動紀錄、工作人員、心得與照片成果。",
        "implemented",
        legacy_definition_id="activity_report_odt",
        linked_document_type="活動成果報告",
        preview_type="activity_result_report",
        evaluation_category="6.社團活動_社團活動",
    ),
    _entry(
        "activity_review_minutes",
        "活動檢討會紀錄",
        ["activity_review_minutes_odt"],
        "專案活動型",
        "ODT",
        "高",
        False,
        True,
        "記錄活動後檢討、改善建議與後續追蹤事項。",
        "partial",
        legacy_definition_id="activity_review_minutes_odt",
        linked_document_type="活動檢討會紀錄",
        evaluation_category="6.社團活動_社團活動",
    ),
    _entry(
        "activity_schedule",
        "活動流程表",
        ["活動粗流程表", "活動細流程表", "activity_rundown_coarse_ods", "activity_rundown_detail_ods"],
        "專案活動型",
        "ODS",
        "中",
        False,
        False,
        "安排活動粗流、細流、器材與現場負責人。",
        "registered_only",
    ),
    _entry(
        "work_assignment",
        "工作分配表",
        ["工作分工表", "staff_assignment_ods"],
        "專案活動型",
        "ODS",
        "高",
        False,
        False,
        "追蹤活動前中後工作項目、負責人與完成狀態。",
        "registered_only",
    ),
    _entry(
        "annual_plan",
        "年度計畫",
        ["annual_plan_odt"],
        "社團運作型",
        "ODT",
        "高",
        False,
        True,
        "規劃社團年度目標、活動、社課、分工與預算。",
        "partial",
        legacy_definition_id="annual_plan_odt",
        linked_document_type="年度計畫",
        evaluation_category="4.社團行政_年度計畫",
    ),
    _entry(
        "officer_roster",
        "社團幹部名冊",
        ["幹部名冊", "cadre_roster_ods"],
        "社團運作型",
        "ODS",
        "高",
        False,
        False,
        "整理幹部職稱、組別、聯絡方式與交接狀態。",
        "registered_only",
    ),
    _entry(
        "member_roster",
        "社員名冊",
        ["member_roster_ods"],
        "社團運作型",
        "ODS",
        "高",
        False,
        False,
        "管理社員資料、社員狀態、社費狀態與聯絡方式。",
        "partial",
        legacy_definition_id="member_roster_ods",
        evaluation_category="3.社團行政_社團資料保存",
    ),
    _entry(
        "course_record",
        "社課紀錄",
        ["course_record_odt"],
        "社團運作型",
        "ODT",
        "高",
        False,
        False,
        "記錄社課內容、出席情形、成果與後續追蹤。",
        "registered_only",
    ),
    _entry(
        "equipment_borrowing_record",
        "器材借用紀錄",
        ["equipment_borrowing_record_ods"],
        "社團運作型",
        "ODS",
        "中高",
        False,
        False,
        "追蹤器材借出、歸還、逾期、損壞與遺失狀態。",
        "registered_only",
    ),
    _entry(
        "expense_budget",
        "經費預算表",
        ["活動預算表", "社團活動預算表", "預算編列表", "活動經費預算表", "經費概算表", "activity_budget_ods"],
        "財務與清冊型",
        "ODS",
        "高",
        True,
        False,
        "編列活動前預算、補助金額、自籌金額與總經費。",
        "implemented",
    ),
    _entry(
        "income_expense_statement",
        "經費收支表",
        ["收支帳冊", "ledger_ods", "收支明細表", "社團經費收支表", "社團帳本", "財務收支表", "經費流水帳", "社團收支明細表"],
        "財務與清冊型",
        "ODS",
        "最高",
        True,
        False,
        "記錄社團日常收入、支出、餘額、代墊與活動結算狀態。",
        "implemented",
    ),
    _entry(
        "expense_settlement",
        "經費收支結算表",
        ["經費收支表", "活動經費結算表", "社團活動經費收支結算表", "經費結算表", "expense_settlement_ods"],
        "財務與清冊型",
        "ODS",
        "最高",
        True,
        False,
        "整理單一活動預算通過金額、實際支出與補助核銷。",
        "implemented",
    ),
    _entry(
        "reimbursement_detail",
        "核銷明細表",
        ["單據明細表", "支出明細表", "收據明細表", "活動核銷明細表", "財務憑證明細表", "reimbursement_detail_ods"],
        "財務與清冊型",
        "ODS",
        "高",
        True,
        False,
        "整理單據、發票、付款方式、墊付款人與憑證狀態。",
        "implemented",
    ),
    _entry(
        "inventory",
        "財產清冊",
        ["inventory_ods"],
        "財務與清冊型",
        "ODS",
        "高",
        False,
        False,
        "整理社團財產、設備現況與保管資料。",
        "registered_only",
    ),
    _entry(
        "subsidy_application",
        "補助申請表",
        ["subsidy_application_odt"],
        "財務與清冊型",
        "ODT",
        "高",
        False,
        False,
        "整理補助申請內容、經費用途與送件附件。",
        "registered_only",
    ),
]


FORMAL_TEMPLATE_REGISTRY_BY_KEY = {
    entry["template_key"]: entry for entry in FORMAL_TEMPLATE_REGISTRY
}
